config/routes.rb
Artweb::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :notices

  root :to => 'static_pages#home'

  match '/rule', to: "static_pages#rule"

   

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  attr_accessible :content, :filenumber, :title

  default_scope order("created_at DESC")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  # GET /notices
  # GET /notices.json
  def index
    notices = Notice.all
    #@notices = Notice.paginate(page: params[:page], :per_page => 15, :order => 'created_at desc')
    @notices = Kaminari.paginate_array(notices).page(params[:page]).per(10)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notices }
    end
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
    @notice = Notice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/new
  # GET /notices/new.json
  def new
    @notice = Notice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/1/edit
  def edit
    @notice = Notice.find(params[:id])
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(params[:notice])

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render json: @notice, status: :created, location: @notice }
      else
        format.html { render action: "new" }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notices/1
  # PUT /notices/1.json
  def update
    @notice = Notice.find(params[:id])

    respond_to do |format|
      if @notice.update_attributes(params[:notice])
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice = Notice.find(params[:id])
    @notice.destroy

    respond_to do |format|
      format.html { redirect_to notices_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def rule
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
	<div class="copyright">
        	<ul>
   				<span>友情链接：</span>
            	<li><a href="#">西南石油大学</a></li>
                <li><a href="#">艺术院首页</a></li>
                <li class="cop">Copyright 软件外包团队</li>
            </ul>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
<!--LOGO-->
    	<div class="logo"><%= image_tag "ArtWeb_03.gif"%></div>
<!--LOGO-->

<!--一级导航 -->
        <div class="nav1">
        	<ul>
            	<li><%= link_to "首页", root_path %></li>
                <li><%= link_to "设备预约", '#'%></li>
                <li><%= link_to "场地预约", '#'%></li>
                <li><%= link_to "视频共享", '#'%></li>
                <li><%= link_to "规章制度", rule_path %></li>
                <li><%= link_to "通知公告", notices_path%></li>
            </ul>
        </div>
<!--一级导航 -->
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artweb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>
</head>
<body>
	<%= render 'layouts/header'%>

	<%= yield %>

	<%= render 'layouts/footer'%>
</body>
</html>

app/views/notices/_form.html.erb
<%= form_for(@notice) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :filenumber %><br />
    <%= f.text_field :filenumber %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notices/_notice.html.erb
<div class="post">
    <h4><%= link_to_unless_current notice.title, notice %>
    	<span><%= notice.created_at.strftime("%Y-%m-%d") %></span>
    </h4>

</div>

app/views/notices/edit.html.erb
<h1>Editing notice</h1>

<%= render 'form' %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<div class="container">
  <h2 align="center">通知公告</h2>
  <br />
  <%= render @notices %>
  <%= paginate @notices %>

<br />

<%= link_to 'New Notice', new_notice_path %>
</div>

app/views/notices/new.html.erb
<h1>New notice</h1>

<%= render 'form' %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<div class="container">
	<%= render :partial => @notice%>
	 <%= @notice.filenumber %>
    <%= simple_format @notice.content %>
<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>
</div>

app/views/static_pages/home.html.erb
<div class="container">
    <!--广告 -->
        <div class="ad">
            <%= image_tag "ArtWeb_07.gif" %>
            
            <div class="notice">
            <!--通知公告-->
            <h1>通知公告</h1>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;艺术院最近将举行歌舞大赛，从<span>10月20日到11月30日</span>，所以舞蹈室都不外借。</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;艺术院最近将举行<span>歌舞大赛</span>，从10月20日到11月30日，所以舞蹈室都不外借。</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;艺术院最近将举行歌舞大赛，从10月20日到11月30日，所以<span>舞蹈室都不外借</span>。</p>
            <h2><a href="#">For more</a></h2>
        </div>
        <!--通知公告-->
        </div>
        
<!--广告 -->
        
        
<!--inform-->
        <div class="infrom">
            <div class="order">
                <ul>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                </ul>
                <h1><a href="#"></a></h1>
            </div>
            <div class="equipment">
                <ul>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                    <li><a href="#">第一放映厅10月23日已被预约<span>2012.10.23</span></a></li>
                </ul>
                <h1><a href="#"></a></h1>
            </div>
            <div class="tel"></div>
        </div>
<!--inform-->

</div>

app/views/static_pages/rule.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="leftspan">
      <!--Sidebar content-->

    </div>
    <div class="span10">
      <!--Body content-->
      
    </div>
  </div>
</div>